flow {
    sources {
        genFlow {
            type = GenerateFile
            config {
                content = "Hello World!"
                pollIntervalMs = 10000
            }
        }
    }
}