flow {
  processors = ${?flow.procesors} {
    ingress {
      type = LogAttribute
      config {
        prefix = "[LAYER 01] "
      }
    }
  }
  connections = ${?flow.connections} {
    genFlow {
      connections {
        success = [ ingress ]
      }
    }
  }
}