flow {
    connections {
        ingress {
            connections {
                success=[
                    REPLACED
                ]
            }
        }
        router {
            connections {
                bulk=[
                    enrich
                ]
                urgent=[
                    elevate
                ]
            }
        }
    }
}
