#flow {
#    sources {
#        genFlow {
#            type = GenerateFlowFile
#            config {
#                content = "Hello World!"
#                pollIntervalMs = 50000
#            }
#        }
#    }
#}